### PR TITLE
Update to latest version of Cirq and pump Python Versions.

### PR DESCRIPTION
**Pull request by dabacon**
Updates to cirq 1.2.0.

Drop support for Python 3.7 and 3.8. Add support for Python 3.10 and 3.11 This matches numpy's deprecation schedule: [nep 19](https://numpy.org/neps/nep-0029-deprecation_policy.html)

### CODE REVIEW

**Review by Cynocracy — APPROVED** [review]

**Comment by Cynocracy** [comment]
Updated branch protection to include 3.10, 3.11, removed 3.7, 3.8

Any idea what's up with mypy?

**Comment by Cynocracy** [comment]
@dabacon  I think you might need to upgrade [the version of mypy](https://github.com/ionq/blqs/blob/0667159d0475e0fc0df5aa607f87c8e90c38eb39/ci/requirements-dev.txt#L6) to [0.981+](https://github.com/python/mypy/issues/13627#issuecomment-1278185109)

**Comment by dabacon** [comment]
Yeah sorry hit the request review a bit early, this also updates to latest version of Cirq and fixes mypy issues.

**Comment by dabacon** [comment]
Thanks @Cynocracy !

**Comment by Cynocracy** [comment]
LGTM!

**Pull request merged**
